{% set name = "jupyterhub" %}
{% set version = "6.0.1" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bafec2f3cfd69cb8b0761986db58ae6d8389fc65a33b2f5ff913276a0300288d
  patches:
    # `pamela` is not available for windows, however mocking.py import it.
    # This breaks tests for windows, so add fallback mechanism stubbing PAMError only when pamela isn't importable.
    - patches/0001-windows-pamela-stub.patch  # [win]

build:
  number: 0
  skip: true  # [py<310]

outputs:
  - name: {{ name }}-base
    # Platform selectors are used intentionally;
    # Jinja conditional are not supported by the current linter.
    script: build-base.sh  # [unix]
    script: build-base.bat  # [win]
    build:
      skip: true  # [py<310]
      entry_points:
        - jupyterhub = jupyterhub.app:main
    requirements:
      host:
        - python
        - pip
        - setuptools >=77
        - setuptools_scm
      run:
        - python
        - aiodns
        - aiohttp
        - alembic >=1.4
        - certipy >=0.1.2
        - idna
        - jinja2 >=2.11.0
        - jupyter_events >=0.11.0
        - oauthlib >=3.0
        - packaging
        - pamela >=1.1.0  # [not win]
        - prometheus_client >=0.5.0
        - psutil >=5.6.5  # [win]
        - pydantic >=2
        - python-dateutil
        - requests
        - sqlalchemy >=1.4.1
        - tornado >=6.5
        - traitlets >=5.4
        - pycurl  # tornado uses pycurl by default, if available
    # configurable-http-proxy >=5.2.0 are needed for this test, which is no in the channel for now,
    # remove once it will be available
    {% set deselected_tests = "--deselect=test_unix_socket.py::test_unix_socket_proxy" %}
    # cannot resolve IP in conda environment
    {% set deselected_tests = deselected_tests + " --deselect=test_proxy.py::test_proxy_bind_ip" %}
    test:
      imports:
        - jupyterhub
        - jupyterhub.alembic
        - jupyterhub.app
        - jupyterhub.apihandlers
        - jupyterhub.auth
        - jupyterhub.authenticators
        - jupyterhub.handlers
        - jupyterhub.log
        - jupyterhub.metrics
        - jupyterhub.oauth
        - jupyterhub.objects
        - jupyterhub.orm
        - jupyterhub.roles
        - jupyterhub.services
        - jupyterhub.scopes
        - jupyterhub.spawner
        - jupyterhub.tests
        - jupyterhub.traitlets
        - jupyterhub.utils
        - jupyterhub._data
        - jupyterhub._memoize
        - jupyterhub._version
      requires:
        - pip
        - pytest >=3.3
        - pytest-asyncio >=0.17,!=0.23.*
        - pytest-rerunfailures
        - requests-mock
        - virtualenv
        - beautifulsoup4
        - cryptography
        - jsonschema
        - jupyterlab >=3
        # configurable-http-proxy missing for proxy tests.
        - configurable-http-proxy >=5.1.0
        # The nbclassic package provides backward-compatible classic notebook endpoints that these tests expect.
        - nbclassic
        - playwright-python
      source_files:
        - jupyterhub/tests
        - pytest.ini
      commands:
        - pip check
        - python -m jupyterhub --help-all
        - jupyterhub -h
        - jupyterhub --version
        - test -f $PREFIX/share/jupyterhub/templates/page.html  # [unix]
        - test -f $PREFIX/share/jupyterhub/static/components/jquery/dist/jquery.min.js  # [unix]
        - test -f $PREFIX/share/jupyterhub/static/css/style.min.css  # [unix]
        - test -f $PREFIX/share/jupyterhub/static/js/home.js  # [unix]
        - dir %PREFIX%\share\jupyterhub\templates\page.html                         || exit 1  # [win]
        - dir %PREFIX%\share\jupyterhub\static\components\jquery\dist\jquery.min.js || exit 1  # [win]
        - dir %PREFIX%\share\jupyterhub\static\css\style.min.css                    || exit 1  # [win]
        - dir %PREFIX%\share\jupyterhub\static\js\home.js                           || exit 1  # [win]
        # Tests requres `pamela` which is not available for windows
        - pytest -vvv --pyargs jupyterhub.tests {{ deselected_tests }}  # [not win]
  - name: {{ name }}-singleuser
    build:
      skip: true  # [py<310]
      entry_points:
        - jupyterhub-singleuser = jupyterhub.singleuser:main
    requirements:
      host:
        - python
        - setuptools >=77
      run:
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3,<5
        - python
    test:
      requires:
        - pip
      imports:
        - jupyterhub.singleuser
      commands:
        - pip check
        - jupyterhub-singleuser --help-all
        - jupyter-lab --version
  - name: {{ name }}
    build:
      skip: true  # [py<310]
    requirements:
      host:
        - python
        - setuptools >=77
      run:
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy
        # NodeJS version specified >=12 (node_min in upstream), raising to 18 for security/EOL.
        - nodejs >=18
        - python
    test:
      requires:
        - pip
      imports:
        - jupyterhub
      commands:
        - pip check
        - jupyterhub --help-all
        - configurable-http-proxy --help

about:
  home: https://hub.jupyter.org
  description: With JupyterHub you can create a multi-user Hub that spawns, manages, and proxies multiple instances of the single-user Jupyter notebook server.
  dev_url: https://github.com/jupyterhub/jupyterhub
  doc_url: https://jupyterhub.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl
  skip-lints:
    # pip check is defined for each output;
    # global tests are ignored in multi-output reccipes.
    - missing_pip_check
    # JupiterLab is used as a runtime component;
    # a CLI smoke test in included instead of launching the GUI.
    - gui_app
