{% set version = "1.5.0" %}

package:
  name: jupyterhub
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: dc618f657c23ba46280e36257e50931806674ba0e9e6498afb091efc6226d69d

build:
  number: 0
  # 6/2/2021: Win32 platform has unsatisfiable dependencies
  # JupyterHub officially does not support Windows,
  # see https://jupyterhub.readthedocs.io/en/stable/installation-basics.html#platform-support
  skip: true  # [win32]
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyterhub = jupyterhub.app:main
    - jupyterhub-singleuser = jupyterhub.singleuser:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - alembic >=1.4
    - async_generator >=1.9
    - certipy >=0.1.2
    - configurable-http-proxy
    - entrypoints
    - jinja2 >=2.11.0,<3.0.0
    - oauthlib >=3.0
    - pamela  # [not win]
    - prometheus_client >=0.4.0
    - psutil  # [win]
    - pycurl
    - python-dateutil
    - requests
    - sqlalchemy >=1.1
    - tornado >=5.1
    - traitlets >=4.3.2
    - jupyter_telemetry >=0.1.0

test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  requires:
    - jupyterhub
    - configurable-http-proxy
    - pip
  commands:
    - pip check
    - python -m jupyterhub --help-all
    - jupyterhub -h
    - configurable-http-proxy -h

about:
  home: https://github.com/jupyterhub/jupyterhub
  dev_url: https://github.com/jupyterhub/jupyterhub
  doc_url: https://jupyterhub.readthedocs.io/en/stable/index.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
