{% set version = "0.7.1" %}

package:
  name: jupyterhub
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: ac99f12636702ce3a18acf2bb3d95aebea0c542354a5382a50affb3f346d5156

build:
  number: 0
  skip: true  # [win or py2k]
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - configurable-http-proxy
    - python
    - traitlets >=4.1
    - tornado >=4.1
    - jinja2
    - pamela
    - sqlalchemy
    - requests

test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  commands:
    - python -m jupyterhub --help-all

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD 3-Clause
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
