{% set version = "0.8.1" %}

package:
  name: jupyterhub
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: 100cf18d539802807a45450d38fefbb376cf1c810f3b1b31be31638829a5c69c

build:
  number: 0
  skip: true  # [win or py2k]
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - configurable-http-proxy
    - python
    - alembic
    - traitlets >=4.3.2
    - tornado >=4.1
    - jinja2
    - pamela
    - python-oauth2 >=1.0
    - sqlalchemy >=1.1
    - requests

test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  commands:
    - python -m jupyterhub --help-all

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD 3-Clause
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
