{% set version = "1.3.0" %}

package:
  name: jupyterhub
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: 05ff701209c340c792cd103606c448c52ace772ece858380905ddd1a2136ee8e

build:
  number: 0
  skip: true  # [py<36]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - alembic
    - async_generator >=1.8
    - certipy>=0.1.2
    - configurable-http-proxy
    - entrypoints
    - jinja2
    - oauthlib>=3.0
    - pamela  # [not win]
    - prometheus_client >=0.0.21
    - psutil  # [win]
    - pycurl
    - python-dateutil
    - requests
    - sqlalchemy >=1.1
    - tornado >=5.0
    - traitlets >=4.3.2
    - jupyter_telemetry

test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  commands:
    - python -m jupyterhub --help-all

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD 3-Clause
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
