{% set version = "5.4.2" %}

package:
  name: jupyterhub-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: acd50f9880c916affe9cddb11be39581fbf5f74971104691f87ef213340d817a

build:
  number: 1
  skip: true  # [py<38]

outputs:
  - name: jupyterhub-base
    script: build-base.sh  # [unix]
    script: build-base.bat  # [win]
    build:
      skip: true  # [py<38]
      entry_points:
        - jupyterhub = jupyterhub.app:main
    requirements:
      host:
        - python
        - pip
        - setuptools >=61
        - setuptools_scm
        - wheel
      run:
        - python
        - alembic >=1.4
        - async_generator >=1.9  # [py<310]
        - certipy >=0.1.2
        - idna
        - importlib_metadata >=3.6  # [py<310]
        - jinja2 >=2.11.0
        - jupyter_events
        - oauthlib >=3.0
        - packaging
        - pamela >=1.1.0  # [not win]
        - prometheus_client >=0.5.0
        - psutil >=5.6.5  # [win]
        - pydantic >=2
        - python-dateutil
        - requests
        - sqlalchemy >=1.4.1
        - tornado >=5.1
        - traitlets >=4.3.2
        - pycurl  # tornado uses pycurl by default, if available
    test:
      imports:
        - jupyterhub
        - jupyterhub.alembic
        - jupyterhub.app
        - jupyterhub.apihandlers
        - jupyterhub.auth
        - jupyterhub.authenticators
        - jupyterhub.handlers
        - jupyterhub.log
        - jupyterhub.metrics
        - jupyterhub.oauth
        - jupyterhub.objects
        - jupyterhub.orm
        - jupyterhub.roles
        - jupyterhub.services
        - jupyterhub.scopes
        - jupyterhub.spawner
        - jupyterhub.tests
        - jupyterhub.traitlets
        - jupyterhub.utils
        - jupyterhub._data
        - jupyterhub._memoize
        - jupyterhub._version
      source_files:
        - jupyterhub/tests
        - pytest.ini
      requires:
        - pip
        # TODO: Enable tests when playwright is available on the main channel.
        # - pytest >=3.3
        # - pytest-asyncio >=0.17,!=0.23.*
        # - pytest-rerunfailures
        # - requests-mock
        # - virtualenv
        # - beautifulsoup4
        # - cryptography
        # - jsonschema
        #- jupyterlab >=3
        # configurable-http-proxy missing for proxy tests.
        #- configurable-http-proxy
        # The nbclassic package provides backward-compatible classic notebook endpoints that these tests expect.
        #- nbclassic
        # playwright is not available on the main channel
        #- playwright
      commands:
        - pip check
        - python -m jupyterhub --help-all
        - jupyterhub -h
        - jupyterhub --version
        - test -f $PREFIX/share/jupyterhub/templates/page.html  # [unix]
        - test -f $PREFIX/share/jupyterhub/static/components/jquery/dist/jquery.min.js  # [unix]
        - test -f $PREFIX/share/jupyterhub/static/css/style.min.css  # [unix]
        - test -f $PREFIX/share/jupyterhub/static/js/home.js  # [unix]
        - dir %PREFIX%\share\jupyterhub\templates\page.html                         || exit 1  # [win]
        - dir %PREFIX%\share\jupyterhub\static\components\jquery\dist\jquery.min.js || exit 1  # [win]
        - dir %PREFIX%\share\jupyterhub\static\css\style.min.css                    || exit 1  # [win]
        - dir %PREFIX%\share\jupyterhub\static\js\home.js                           || exit 1  # [win]
        # Need playwright to run test suite.
        # - pytest -vvv --pyargs jupyterhub.tests

  - name: jupyterhub-singleuser
    build:
      skip: true  # [py<38]
      entry_points:
        - jupyterhub-singleuser = jupyterhub.singleuser:main
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3,<5
        - python
    test:
      requires:
        - pip
      imports:
        - jupyterhub.singleuser
      commands:
        - pip check
        - jupyterhub-singleuser --help-all

  - name: jupyterhub
    build:
      skip: true  # [py<38]
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy
        # NodeJS version specified >=12 (node_min in upstream), raising to 18 for security/EOL.
        - nodejs >=18
        - python
    test:
      requires:
        - pip
      imports:
        - jupyterhub
      commands:
        - pip check
        - jupyterhub --help-all
        - configurable-http-proxy --help

about:
  home: https://hub.jupyter.org
  description: With JupyterHub you can create a multi-user Hub that spawns, manages, and proxies multiple instances of the single-user Jupyter notebook server.
  dev_url: https://github.com/jupyterhub/jupyterhub
  doc_url: https://jupyterhub.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl
