{% set version = "4.0.2" %}

package:
  name: jupyterhub-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: d4e450eed8d90dfbcf0eca08f00f2093a0bce74dc51f7cfc0b7057f602341a1d

build:
  number: 0
  skip: true  # [py<37 or s390x]

outputs:
  - name: jupyterhub-base
    script: build-base.sh   # [unix]
    script: build-base.bat  # [win]
    build:
      skip: true  # [py<37 or s390x]
      entry_points:
        - jupyterhub = jupyterhub.app:main
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - alembic >=1.4
        - importlib_metadata >=3.6  # [py<310]
        - async_generator >=1.9
        - certipy >=0.1.2
        - jinja2 >=2.11.0
        - oauthlib >=3.0
        - pamela  # [not win]
        - prometheus_client >=0.4.0
        - psutil >=5.6.5 # [win]
        - python-dateutil
        - requests
        - packaging
        - sqlalchemy >=1.4
        - tornado >=5.1
        - traitlets >=4.3.2
        - jupyter_telemetry >=0.1.0
        - pycurl # tornado uses pycurl by default, if available
    test:
      imports:
        - jupyterhub
        - jupyterhub.apihandlers
        - jupyterhub.handlers
        - jupyterhub.tests
        - jupyterhub.app
      requires:
        - pip
      commands:
        - pip check
        - python -m jupyterhub --help-all
        - jupyterhub -h

  - name: jupyterhub-singleuser
    build:
      skip: true  # [py<37 or s390x]
      entry_points:
        - jupyterhub-singleuser = jupyterhub.singleuser:main
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3,<5
        - python
    test:
      requires:
        - pip
      imports:
        - jupyterhub.singleuser
      commands:
        - pip check
        - jupyterhub-singleuser --help-all

  - name: jupyterhub
    build:
      skip: true  # [py<37 or s390x]
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy
        - nodejs >=12
        - python
    test:
      requires:
        - pip
      imports:
        - jupyterhub
      commands:
        - pip check
        - jupyterhub --help-all
        - configurable-http-proxy --help

about:
  home: https://github.com/jupyterhub/jupyterhub
  description: |
    With JupyterHub you can create a multi-user Hub that spawns, manages, and proxies multiple instances of the single-user Jupyter notebook server.
  dev_url: https://github.com/jupyterhub/jupyterhub
  doc_url: https://jupyterhub.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl
