{% set version = "3.1.0" %}

package:
  name: jupyterhub
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: eaf8735c32efd05c00aecc860b953f731af559d6e046b621b1802f850475626f

build:
  number: 0
  # 6/2/2021: Win32 platform has unsatisfiable dependencies
  # JupyterHub officially does not support Windows,
  # see https://jupyterhub.readthedocs.io/en/stable/installation-basics.html#platform-support
  skip: true  # [win32 or s390x]
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyterhub = jupyterhub.app:main
    - jupyterhub-singleuser = jupyterhub.singleuser:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - alembic >=1.4
    - importlib-metadata >=3.6. # [py<310]
    - async_generator >=1.9
    - certipy >=0.1.2
    - configurable-http-proxy
    - jinja2 >=2.11.0,<3.0.0
    - oauthlib >=3.0
    - pamela  # [not win]
    - prometheus_client >=0.4.0
    - psutil >=5.6.5 # [win]
    - python-dateutil
    - requests
    - packaging
    - sqlalchemy >=1.1
    - tornado >=5.1
    - traitlets >=4.3.2
    - jupyter_telemetry >=0.1.0
    
test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  requires:
    - jupyterhub
    - configurable-http-proxy
    - pip
  commands:
    - pip check
    - python -m jupyterhub --help-all
    - jupyterhub -h
    - configurable-http-proxy -h

about:
  home: https://github.com/jupyterhub/jupyterhub
  description: |
    With JupyterHub you can create a multi-user Hub that spawns, manages, and proxies multiple instances of the single-user Jupyter notebook server.
  dev_url: https://github.com/jupyterhub/jupyterhub
  doc_url: https://jupyterhub.readthedocs.io/en/stable/index.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl