{% set version = "5.2.1" %}

package:
  name: jupyterhub-feedstock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: 5b35444c2c254e60563887d1d59c2376813d16a166ec6e0a410c773cdbd37ebd

build:
  number: 0
  noarch: python

outputs:
  - name: jupyterhub-base
    build:
      noarch: python
      script: python -m pip install . --no-deps -vv
      entry_points:
        - jupyterhub = jupyterhub.app:main
        - jupyterhub-singleuser = jupyterhub.singleuser:main
    requirements:
      host:
        - python >=3.10
        - setuptools
        - pip
      run:
        - alembic >=1.4
        - certipy >=0.1.2
        - jinja2 >=2.11.0
        - jupyter_events
        - oauthlib >=3.0
        - packaging
        - pamela
        - psutil
        - prometheus_client >=0.5.0
        - pydantic >=2
        - python >=3.10
        - python-dateutil
        - requests
        - sqlalchemy >=1.4.1
        - tornado >=5.1
        - traitlets >=4.3.2
      run_constrained:
        - psutil >=5.6.5

    test:
      requires:
        - pip
      imports:
        - jupyterhub
        - jupyterhub.apihandlers
        - jupyterhub.handlers
        - jupyterhub.tests
        - jupyterhub.app
      commands:
        - pip check
        - jupyterhub --help-all
        - test -f $PREFIX/share/jupyterhub/templates/page.html
        - test -f $PREFIX/share/jupyterhub/static/components/jquery/dist/jquery.min.js
        - test -f $PREFIX/share/jupyterhub/static/css/style.min.css
        - test -f $PREFIX/share/jupyterhub/static/js/home.js

  - name: jupyterhub-singleuser
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3.1
        - python >=3.8
    test:
      requires:
        - pip
      imports:
        - jupyterhub.singleuser
      commands:
        - pip check
        - jupyterhub-singleuser --help-all

  - name: jupyterhub
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy >=4
        - nodejs >=12
        - psutil  # undeclared extra, used preferentially for logging
        - pycurl  # undeclared extra, used preferentially for performance
        - python >=3.8
    test:
      requires:
        - pip
      imports:
        - jupyterhub
      commands:
        - pip check
        - jupyterhub --help-all
        - configurable-http-proxy --help  # [not win]

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks
  doc_url: https://jupyterhub.readthedocs.io

extra:
  feedstock-name: jupyterhub
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl
