{% set version = "2.2.0" %}

package:
  name: jupyterhub
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: 6aa7f15a5e198fa8aad8167a755508593e47719e7950fc09d7d1281b962343a4

build:
  number: 0
  # 2021/6/2: Win32 platform has unsatisfiable dependencies
  # JupyterHub officially does not support Windows,
  # see https://jupyterhub.readthedocs.io/en/stable/installation-basics.html#platform-support
  # 2021/12/15: This package isn't included in SOW Packages list, and there isn't configurable-http-proxy >=4.0.0 on s390x
  skip: true  # [win32 or s390x]
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyterhub = jupyterhub.app:main
    - jupyterhub-singleuser = jupyterhub.singleuser:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - alembic >=1.4
    - async_generator >=1.9
    - certipy >=0.1.2
    - configurable-http-proxy >=4.0.0
    - entrypoints
    - jinja2 >=2.11.0
    - jupyter_telemetry >=0.1.0
    - oauthlib >=3.0
    - packaging
    - pamela
    - prometheus_client >=0.4.0
    - psutil >=5.6.5
    - pycurl
    - python-dateutil
    - requests
    - sqlalchemy >=1.1
    - tornado >=5.1
    - traitlets >=4.3.2

test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  requires:
    - jupyterhub
    - configurable-http-proxy
    - pip
  commands:
    - pip check
    - python -m jupyterhub --help-all
    - jupyterhub -h
    - configurable-http-proxy -h
    - test -f $PREFIX/share/jupyterhub/templates/page.html
    - test -f $PREFIX/share/jupyterhub/static/components/jquery/dist/jquery.min.js
    - test -f $PREFIX/share/jupyterhub/static/css/style.min.css
    - test -f $PREFIX/share/jupyterhub/static/js/home.js

about:
  home: https://github.com/jupyterhub/jupyterhub
  dev_url: https://github.com/jupyterhub/jupyterhub
  doc_url: https://jupyterhub.readthedocs.io/en/stable/index.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
