{% set version = "0.9.2" %}

package:
  name: jupyterhub
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: c7d042cf779227f874804eca77db66bc5b61d5b0902ae2a62b17578b3ea21fd1

build:
  number: 0
  skip: true  # [py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - alembic
    - async_generator >=1.8
    - configurable-http-proxy
    - jinja2
    - pamela  # [not win]
    - prometheus_client >=0.0.21
    - psutil  # [win]
    - pycurl
    - python-dateutil
    - python-oauth2 >=1.0
    - requests
    - sqlalchemy >=1.1
    - traitlets >=4.3.2
    - tornado >=5.0
    
test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  commands:
    - python -m jupyterhub --help-all

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD 3-Clause
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
