travis:
  secure:
    BINSTAR_TOKEN: ezQ1jvkBRQYJAPtch7WkszwbUnZQiWklWSC7h5RsAF+aobD28F20vpUePWG2HJE4+igIE0ukJog/No1ZFTkfoOGmS3pkMLi09Mjo/eBN2SEOwVsM0L4oaBrgd8kHDoEXhNLY01oTYmhgioEeQgLXO06mBSeEvIiVwWNVRC5jaX/QlUKQj3swIqd8/PjRyrINCjMzNmwTe9l9kMXtP1QDGmRVIWqx//WSKH5cD/5RTmKF5QjzuMFf6HDZyov+/g2Qr1i6nwNdZTSckMIcdb+76LQEQpCYWeJW02eZSFYvynfZD6Uw69Lr/SR9GQ112061azHp+tZvtvkTH64aMJt/k0SVh7wuKnsyyJyE2vJYKEy+pIjUoHH+80m1anWDD/Wp0fNlOXWmxbtRglt5rvV6vb7O7BMasLI2ow4l5REY8+r1FxZL5k+DzEP3owlSwVhFqsUeYt1bWJvnroAaKdrsBv7voX9+3lsk/WnCB43UkLAW/nQtmQ4W7E/ahk9ZlFJ/xMwM4WwxJiMoIhhm1s1B7+qRgBuHU15m27BLGPOmyL9j2qwbbplZx1ZcYy4OLT6njCy6JmlAfLiI4y8bqhol9z7HKBa2Vocx3sWDKdBjEV9eK8q/ZYTiQXEa+Ub0GSWusdjZc08TU65WKN6btx1qP/wjsXPWbBCEuNjJbAi6Cp8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
