travis:
  secure:
    BINSTAR_TOKEN: IkA+qR4Wb4m93LrXkKGmzh3Khs69+ww3FK8mmnaK+X9SGAC5ANwMMuZnGQ6+tqOnmqL44KD/rWrkli/+UQ4dGvkvAXbdT4czPTQzDrO56kah3X6VJKRr/K6hhM0Z677I9Ely58RNZJpkeWFllAEp8uzPY151CN0Jbp2QRalSqDedS7gclto94D22Tff326RhvP1XU877T2MGKg3eIZCjujmt96RF3oeRa7BgOKVmNqW2cEGDGjqk6zMPY5HUyv2j7DKOoD9ITfDUCVH/W1P4WHM5cIHibkqdxBYktsb/P2x6xOOwTh8jRM0zEfvOZsnwcC+14YhLgDkZXfXMskbaduv6VotIxmvxViM75l+vJs9mALT787cP7fwFbN8ouXTVPyVN4pEDgaLlCBrzyDMhfNc60j1AiGISUbz+Cw89ma9RwzYX4gbACbhGSik+TTyqhXH4MrLRB7UY++lxbWZBpMmBILGV/mD6bmtXkX+0H4+uSUt6DQN1HQReS97ktu8mkd8NAcIUg5r+ml4arVwRmy6/K1L4DyifFxzj1aZRCLGgrlBEvvVXv6P5WF1y9pte9+B0VJJJb3rhKsDdbBEVx2rOhmKseoL647Cm7WaaTeXlr1AKxngold6MFPPnuGwnti0OoHS7V3eNmm+Y7/A9agHFeZ2bwoqn1NVGF6mFw74=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
